### ISSUE TITLE
"Unexpected token import" with `ngc`  for angular universal

### ISSUE THREAD

**Issue by aaronte** [angulartics/angulartics2#138]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
Running `ngc` for `angular-universal` fails importing `angulartics2`

* **What is the expected behavior?**
Importing should work fine

* **What is the motivation / use case for changing the behavior?**
`angulartics` should be compatible with projects that use angular universal

* **Please tell us about your environment:**
Angular version: 4.1.3

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

```js
/Users/aaronte/Workspace/web-client/node_modules/angulartics2/dist/core/angulartics2.js:1
(function (exports, require, module, __filename, __dirname) { import { Injectable } from '@angular/core';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
```

**Comment by aaronte** [comment]
https://github.com/angulartics/angulartics2/pull/139 takes care of this error.

**Comment by mfonolleda** [comment]
Hi @aaronte , we've ran into this issue as well. Do you have any updates as to when your fix will go into a release?

**Comment by aaronte** [comment]
@mfonolleda  Not sure. Depends on the project owners.

**Comment by mfonolleda** [comment]
Thnx @aaronte. If you know any workarounds it'd be very useful.

**Comment by aaronte** [comment]
@mfonolleda I think this should be fixed on https://github.com/angulartics/angulartics2/releases/tag/v2.4.0

**Comment by mfonolleda** [comment]
@aaronte, upgraded to 2.4.0 but still getting the same error. We are using the following angular universal-starter project (cli) below, to which we've added angulartics2 (in package.json, app.module.ts and app.component.ts as in angulartics2 doc)
[https://github.com/angular/universal-starter/tree/master/cli](url)

Are we missing something?

**Comment by sylvaindumont** [comment]
With v2.4.0 it doesn't work by default, but the following import works
```typescript
import { Angulartics2, Angulartics2Piwik } from 'angulartics2/dist/es5';
```

**Comment by dockleryxk** [comment]
My build words with @sylvaindumont's advice, but my node server crashes because of the same error.

**Comment by scttcper** [comment]
fixed in #154 coming with v3
